Wish/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from .views import home, debug

admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^account/', include('account.urls')),
    url(r'^task/', include('task.urls'),  name='home'),
    #url(r'^msg/', include('msg.urls')),
    #url(r'^$', home, name='home'),
    #url(r'^trix/',include('trix.urls')),
    #url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

account/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from .forms import SigninForm
from . import views
from Wish.settings import LOGIN_URL



app_name='account'

urlpatterns = [
    #url(r'^signin/$', auth_views.login, {'template_name': 'signin.html', 'authentication_form': SigninForm},name='signin'),
    url(r'^signin/$', views.signin, name='signin'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^logout/$', auth_views.logout,{'template_name': 'signin.html', 'next_page': LOGIN_URL}, name='logout'),
]

account/models.py
from __future__ import unicode_literals
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User





class Unit(models.Model):

    name = models.CharField(max_length=10, unique=True)

    def __str__(self):
        return '%s' % (self.name)



class Employee(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE)
    manager = models.ForeignKey('self',on_delete=models.SET_NULL, blank=True, null=True)
    is_manager = models.BooleanField(default=False, blank=True)
    is_continuous_improvement_officer= models.BooleanField(default=False, blank=True)
    subscribed_to_newsletter = models.BooleanField(default=False, blank=True)


    def __str__(self):
        return '%s %s' % (self.user.first_name, self.user.last_name)


    # overriden to delete OneToOneField user
    def delete(self, *args, **kwargs):
        self.user.delete()
        return super(self.__class__, self).delete(*args, **kwargs)

account/forms.py
from django import forms
from .models import Unit, Employee
from django.contrib.auth.models import User
from django.contrib.auth.password_validation  import validate_password
import re
from django.contrib.auth import authenticate, login



class SigninForm(forms.Form):

    def __init__(self, *args, **kwargs):
        super(SigninForm, self).__init__(*args, **kwargs)
        self.fields.keyOrder = ['username', 'password']


    username = forms.CharField(
        label="Username",
        max_length=30,
        required=True,
        error_messages={'required': 'Please provide your username'},
        widget=forms.TextInput(
            attrs={
                'type':'text',
                'name': 'username',
                'placeholder':'Donald',
            }
        )
    )

    password = forms.CharField(
        label="Password",
        max_length=30,
        required=True,
        error_messages={'required': 'Please provide your password'},
        widget=forms.TextInput(
            attrs={
                'type':'password',
                'name': 'password',
                'placeholder':'ThatsAllFolks',
                'class':'form-control'
            }
        )
    )


    def clean(self):

        # get field values
        cleaned_data = super().clean()
        username = cleaned_data.get("username")
        password = cleaned_data.get("password")

        if username:
            # check if username is registered
            qs = User.objects.filter(username=username)

            if not qs.exists():
                raise forms.ValidationError(
                    {'username':'Sorry, that username is not registered'})

        if password:
            # check if password match with username
            user = authenticate(username=username, password=password)
            if user is None:
                raise forms.ValidationError(
                    {'password':'Sorry, that password does not match given username'})

        # OK
        return self.cleaned_data





class SignupForm(forms.Form):

    first_name = forms.CharField(
        error_messages={'required':'Please provide your first name'},
        label="First name",
        max_length=30,
        required=True,
        widget=forms.TextInput(
            attrs={
                'type': 'text',
                'name': 'first_name',
                'placeholder': 'Donald',
                'class': 'form-control has-feedback-left'
            }
        ),
    )

    last_name = forms.CharField(
        error_messages={'required': 'Please provide your last name'},
        label="Last name",
        max_length=30,
        required=True,
        widget=forms.TextInput(
            attrs={
                'type': 'text',
                'name': 'last_name',
                'placeholder': 'McDuck',
                'class': 'form-control has-feedback-right'
            }
        ),
    )

    username = forms.CharField(
        error_messages={'required': 'Please provide your username'},
        label="Username",
        max_length=30,
        required=True,
        widget=forms.TextInput(
            attrs={
                'type':'text',
                'name': 'username',
                'placeholder':'donald',
            }
        )
    )

    password = forms.CharField(
        error_messages={'required': 'Please provide a password'},
        label="Password",
        max_length=30,
        required=True,
        widget=forms.TextInput(
            attrs={
                'type':'password',
                'name': 'password',
                'placeholder':'ThatsAllFolks',
                'class':'form-control'
            }
        )
    )

    email = forms.CharField(
        error_messages={'required': 'Please provide your email'},
        label="Email",
        max_length=30,
        required=True,
        widget=forms.TextInput(
            attrs={
                'type':'email',
                'name': 'email',
                'placeholder':'donald.mcduck@disney.com',
                'class':'form-control',
                #'pattern': "^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@disney[.]com$",
            }
        )
    )


    unit = forms.ModelChoiceField(
        error_messages={'required': 'Please provide your unit'},
        queryset=Unit.objects.all(),
        required=True,
        widget=forms.Select(
            attrs={
                'name': 'unit',
                'class': 'form-control'
            }
        )
    )


    manager = forms.ModelChoiceField(
        queryset=Employee.objects.filter(is_manager=True),
        required=False,
        widget=forms.Select(
            attrs={
                'name': 'manager',
                'class': 'form-control'
            }
        )
    )

    is_manager=forms.BooleanField(
        label="I manage a team",
        required=False,
        initial=False,
        widget=forms.CheckboxInput(
            attrs={
                'name': 'is_manager'
            }
        )
    )

    is_continuous_improvement_officer=forms.BooleanField(
        label="I manage continous improvement",
        required=False,
        initial=False,
        widget=forms.CheckboxInput(
            attrs={
                'name': 'is_continuous_improvement_officer'
            }
        )
    )


    subscribed_to_newsletter = forms.BooleanField(
        label="Subscribe to newsletter",
        required=False,
        initial=False,
        widget=forms.CheckboxInput(
            attrs={
                'name': 'subscribed_to_newsletter'
            }
        )
    )


    # check given username is unique (not already used by another employee)
    def clean_username(self):

        username = self.cleaned_data['username']


        if username:
            qs = User.objects.filter(username=username)

            if qs.exists():
                raise forms.ValidationError(
                    'Sorry, that username is already in use, please forward another one')

        return username


    # check complexity of given password using django utility functions
    def clean_password(self):

        new_password=(self.cleaned_data['password'])

        # use django contrib password validators, listed in setting.py|AUTH_PASSWORD_VALIDATORS
        # raise ValidationError if one of the validators fails
        validate_password(new_password)

        return self.cleaned_data['password']


    # check e-mail format and uniqueness
    def clean_email(self):

        # get posted email
        new_email=self.cleaned_data['email']

        # check email format + domain
        pattern=re.compile("^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@disney[.]com$")
        if not pattern.match(new_email):
            raise forms.ValidationError(
                'Sorry, only @disney.com domain are authorized')

        # check that given  email is not already in use
        qs = User.objects.filter(email=new_email)
        if qs.exists():
            raise forms.ValidationError(
                'Sorry, that email is already in use, please forward another one')


        return self.cleaned_data['email']



'''class ProfileForm(forms.Form):

    def __init__(self, user, *args, **kwargs):

        # get instance of the employee that is editing his/her profile
        self.employee = Employee.objects.filter(user__pk=user.pk)[0]



    first_name = forms.CharField(
        label="First name",
        max_length=30,
        required=True,
        widget=forms.TextInput(
            attrs={
                'type': 'text',
                'name': 'first_name',
                'placeholder': 'First name',
                'class': 'form-control has-feedback-left'
            }
        ),
    )

    last_name = forms.CharField(
        label="Last name",
        max_length=30,
        required=True,
        widget=forms.TextInput(
            attrs={
                'type': 'text',
                'name': 'last_name',
                'placeholder': 'Last name',
                'class': 'form-control has-feedback-right'
            }
        ),
    )

    username = forms.CharField(
        label="Username",
        max_length=30,
        required=True,
        widget=forms.TextInput(
            attrs={
                'type':'text',
                'name': 'username',
                'placeholder':'User name',
            }
        )
    )

    password = forms.CharField(
        label="Password",
        max_length=30,
        required=True,
        widget=forms.TextInput(
            attrs={
                'type':'password',
                'name': 'password',
                'placeholder':'Password',
                'class':'form-control'
            }
        )
    )

    email = forms.CharField(
        label="Email",
        max_length=30,
        required=True,
        widget=forms.TextInput(
            attrs={
                'type':'email',
                'name': 'email',
                'placeholder':'donald.mcduck@disney.com',
                'class':'form-control',
                #'pattern': "^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@disney[.]com$",
            }
        )
    )


    unit = forms.ModelChoiceField(
        queryset=Unit.objects.all(),
        required=True,
        widget=forms.Select(
            attrs={
                'name': 'unit',
                'class': 'form-control'
            }
        )
    )


    manager = forms.ModelChoiceField(
        queryset=Employee.objects.filter(is_manager=True),
        required=False,
        widget=forms.Select(
            attrs={
                'name': 'manager',
                'class': 'form-control'
            }
        )
    )

    is_manager=forms.BooleanField(
        label="I manage a team",
        required=False,
        initial=False,
        widget=forms.CheckboxInput(
            attrs={
                'name': 'is_manager'
            }
        )
    )

    is_continuous_improvement_officer=forms.BooleanField(

account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required


def signin(request):

    from .forms import SigninForm
    from django.contrib.auth import authenticate, login

    if request.method == "POST":

        # handles form submitted by user
        form = SigninForm(request.POST)


        if form.is_valid():

            # get data provided by user
            cleaned_data = form.cleaned_data

            # get credentials
            username=cleaned_data['username']
            password=cleaned_data['password']

            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)

                # redirect employee to home
                return redirect("task:list")

    else:
        # delivers a blank form to be filled in
        form = SigninForm()

    # render form using given html template
    return render(request, 'signin.html', {'form': form})


def signup(request):

    from django.contrib.auth.models import User
    from .models import Employee
    from .forms import SignupForm


    employee_fields=['unit',
                     'manager',
                     'is_manager',
                     'is_continuous_improvement_officer',
                     'subscribed_to_newsletter']

    if request.method == "POST":

        # if user strikes cancel, redirect to sigin view
        if request.POST.get("cancel"):
            return redirect('account:signin')


        # handles form submitted by user
        form = SignupForm(request.POST)


        if form.is_valid():

            # get data provided by user
            cleaned_data = form.cleaned_data

            # create new user
            user=User.objects.create_user(
                first_name=cleaned_data['first_name'],
                last_name = cleaned_data['last_name'],
                username = cleaned_data['username'],
                password = cleaned_data['password'],
                email = cleaned_data['email']
            )

            # save user in database
            user.save()

            # create new employee
            employee = Employee(user=user)
            for field in employee_fields:
                setattr(employee, field, cleaned_data[field])

            # save employee
            employee.save()

            # if everything goes well, redirect employee to signin page
            return redirect("account:signin")

    else:
        # delivers a blank form to be filled in
        form = SignupForm()


    # render form using given html template
    return render(request, 'signup.html', {'form': form})



@login_required
def profile(request):

    from django.contrib.auth.models import User
    from .models import Employee
    from .forms import ProfileForm


    user_fields=     ['first_name',
                     'last_name',
                     'username',
                     'password',
                     'email']
    employee_fields=['unit',
                     'manager',
                     'is_manager',
                     'is_continuous_improvement_officer',
                     'subscribed_to_newsletter']

    # get instance of the user that is editing his/her profile
    user = request.user

    # get instance of the employee that is editing his/her profile
    employee = Employee.objects.filter(user__pk=user.pk)[0]


    if request.method == "POST":

        # if user strikes cancel, redirect to task list
        if request.POST.get("cancel"):
            return redirect('task:list')

        # handles form submitted by user
        form = ProfileForm(request.POST)

        # validate form
        form.clean()

        if form.is_valid():

            # get data provided by user
            cleaned_data = form.cleaned_data



            # update userfields
            for field in user_fields:
                setattr(user, field, cleaned_data[field])

            # save user changes in database
            user.save()

            # update userfields
            for field in employee_fields:
                setattr(employee, field, cleaned_data[field])

            # save employee changes in database
                employee.save()

            # if everything goes well, redirect employee to task list
            return redirect('task:list')

    else:

        context={'first_name':employee.user.first_name,
                 'last_name':employee.user.last_name,
                 'username':employee.user.username,
                 'password':employee.user.password,
                 'email':employee.user.email,
                 'unit':employee.unit,
                 'manager':employee.manager,
                 'is_manager':employee.is_manager,
                 'is_continuous_improvement_officer':employee.is_continuous_improvement_officer,
                 'subscribed_to_newsletter':employee.subscribed_to_newsletter,
                }
        # delivers a blank form to be filled in
        form = ProfileForm(context)


    # render form using given html template
    return render(request, 'profile.html', {'form': form})

account/templates/profile.html
{% extends "base_site.html" %}

{% load widget_tweaks %}

{% load static %}



{% block extra_css_files %}
  <link href="{% static "css/signup.css" %}" rel="stylesheet">
{% endblock extra_css_files %}

{% block extra_javascripts %}
{% endblock extra_javascripts %}


{% block title %} Edit your profile {% endblock title %}


{% block body %}



    <div class="container" style="margin: 10px"><div class="row"><div class="col-md-offset-3 col-md-6 col-xs-12  "><div class="x_panel">
        <div class="x_title">
            <h1>Edit your profile</h1>
        </div>

        <div class="x_content">


            <form id="signupForm" method="post" action="{% url 'account:profile' %}" class="form-horizontal form-label-left" novalidate>
                {% csrf_token %}

                <div class="col-md-6 col-sm-6 col-xs-12 form-group ">
                    {{ form.first_name }}
                    <span class="fa fa-user form-control-feedback left" aria-hidden="true"></span>
                </div>

                <div class="col-md-6 col-sm-6 col-xs-12 form-group has-feedback">
                    {{ form.last_name }}
                    <span class="fa fa-user form-control-feedback right" aria-hidden="true"></span>
                </div>

                <br /> <br /> <br />

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">{{ form.username.label }}</label>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        {% if form.is_bound %}
                            {% if form.username.errors %}
                                {% render_field form.username class="form-control is-invalid" %}
                                {% for error in form.username.errors %}
                                    <div class="invalid-feedback">
                                        {{ error }}
                                    </div>
                                {% endfor %}

                            {% else %}
                                {% render_field form.username class="form-control is-valid" %}
                            {% endif %}
                        {% else %}
                            {% render_field form.username class="form-control" %}
                        {% endif %}
                     </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">{{ form.password.label }} </label>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        {% if form.is_bound %}
                            {% if form.password.errors %}
                                {% render_field form.password class="form-control is-invalid" %}
                                {% for error in form.password.errors %}
                                    <div class="invalid-feedback">
                                        {{ error }}
                                    </div>
                                {% endfor %}
                            {% else %}
                                {% render_field form.password class="form-control is-valid" %}
                            {% endif %}
                        {% else %}
                            {% render_field form.password class="form-control" %}
                        {% endif %}
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">{{ form.email.label }} </label>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        {% if form.is_bound %}
                            {% if form.email.errors %}
                                {% render_field form.email class="form-control is-invalid" %}
                                {% for error in form.email.errors %}
                                    <div class="invalid-feedback">
                                        {{ error }}
                                    </div>
                                {% endfor %}
                            {% else %}
                                {% render_field form.email class="form-control is-valid" %}
                            {% endif %}
                        {% else %}
                            {% render_field form.email class="form-control" %}
                        {% endif %}
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">{{ form.unit.label }}</label>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        {{ form.unit }}
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">{{ form.manager.label }}</label>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        {{ form.manager }}
                    </div>
                </div>


                <div class="form-group ">
                    <label class="col-md-3 col-sm-3 col-xs-12 control-label"> I manage </label>

                    <div class="col-md-9 col-sm-9 col-xs-12">
                       {{ form.is_manager }} a team
                        {{ form.is_continuous_improvement_officer }} continuous improvement

                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">{{ form.subscribed_to_newsletter.label }}</label>
                    <div class="col-offset-1 col-md-1 col-sm-1 col-xs-1">
                        {{ form.subscribed_to_newsletter }}
                    </div>
                </div>


                <div class="form-group ln_solid"></div>
                     <button id="submit-button" type="submit" name="submit" value="profile" class="btn btn-success pull-right" >Submit</button>
                     <button id="cancel-button"  type="cancel" name="cancel" value="profile" class="btn btn-primary pull-right" >Cancel</button>
                </div>

            </form>
        </div>
    </div></div></div></div>



{% endblock body %}

account/templates/signin.html
{% extends "base_site.html" %}

{% load widget_tweaks %}

{% load static %}


{% block extra_css_files %}
  <link href="{% static "css/signup.css" %}" rel="stylesheet">
{% endblock extra_css_files %}

{% block extra_javascripts %}
{% endblock extra_javascripts %}


{% block title %} Sign in ! {% endblock title %}


{% block body %}

    <div class="container" style="margin: 10px"><div class="row"><div class="col-md-offset-3 col-md-6 col-xs-12  "><div class="x_panel">
        <div class="x_title">
            <h1>Login</h1>
        </div>

        <div class="x_content">


            <form id="signinForm" method="post" action="{% url 'account:signin' %}" class="form-horizontal form-label-left" novalidate>
                {% csrf_token %}

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">{{ form.username.label }}</label>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        {% if form.is_bound %}
                            {% if form.username.errors %}
                                {% render_field form.username class="form-control is-invalid" %}
                                {% for error in form.username.errors %}
                                    <div class="invalid-feedback">
                                        {{ error }}
                                    </div>
                                {% endfor %}

                            {% else %}
                                {% render_field form.username class="form-control is-valid" %}
                            {% endif %}
                        {% else %}
                            {% render_field form.username class="form-control" %}
                        {% endif %}
                     </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">{{ form.password.label }} </label>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        {% if form.is_bound %}
                            {% if form.password.errors %}
                                {% render_field form.password class="form-control is-invalid" %}
                                {% for error in form.password.errors %}
                                    <div class="invalid-feedback">
                                        {{ error }}
                                    </div>
                                {% endfor %}
                            {% else %}
                                {% render_field form.password class="form-control is-valid" %}
                            {% endif %}
                        {% else %}
                            {% render_field form.password class="form-control" %}
                        {% endif %}
                    </div>
                </div>

                <div class="separator">
                <div class="form-group">
                    <div class="float-left">
                        <a href="{% url 'account:signup' %}" > Create Account </a>
                    </div>
                    <div class="float-right">
                        <button id="submit-button" type="submit" name="signin" value="signin" class="btn btn-success pull-right">Submit</button>
                    </div>
                </div> </div>
            </form>
        </div>
    </div></div></div></div>




{% endblock body %}