Wish/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from .views import home, debug

admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^account/', include('account.urls')),
    url(r'^task/', include('task.urls'),  name='home'),
    #url(r'^msg/', include('msg.urls')),
    #url(r'^$', home, name='home'),
    #url(r'^trix/',include('trix.urls')),
    #url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

task/urls.py
from django.conf.urls import url
from . import views

app_name='task'

urlpatterns = [
    url(r'^$', views.list, name='list'),
    url(r'^create/$', views.create, name='create'),
    #url(r'^(?P<pk>\d+)/validate/$', views.validate, name='validate'),
    url(r'^(?P<pk>\d+)/edit_wizard/(?P<page>\d+)/$', views.edit_wizard, name='edit_wizard'),
    #url(r'^(?P<pk>\d+)/edit/(?P<page>\d+)/$', views.edit, name='edit'),
    url(r'^(?P<pk>\d+)/delete/$', views.delete, name='delete'),
]

task/forms.py
from django import forms
from .models import Task
from account.models import Employee, Unit
import datetime
from Wish.widgets import QuillWidget,  DatePickerWidget
import json
from Wish import settings
from django.forms.utils import ErrorDict






class CreateForm(forms.Form):


    headline = forms.CharField(
        error_messages={'required':'Please provide a headline'},
        label="Headline",
        max_length=30,
        required=True,
        widget=forms.Textarea(
            attrs={
                'type': 'text',
                'name': 'headline',
                'placeholder': 'Short description',
                'rows': '1',
                'class': 'form-control has-feedback-left',
                'style': 'resize:none;'
            }
        ),
    )

    problem = forms.CharField(
        label="Problem",
        max_length=1000,
        required=False,
        widget=QuillWidget(
            attrs={
                'placeholder': 'Short description',
            }
        ),
    )

    proposal = forms.CharField(
        error_messages={'required': 'Please provide your proposal'},
        label="Proposal",
        max_length=1000,
        required=True,
        widget=QuillWidget(
            attrs={
                'placeholder': 'Short description',
                'class': 'form-control has-feedback-left',
            }
        ),
    )

    validator = forms.ModelChoiceField(
        error_messages={'required': 'Please provide a validator'},
        label="Validator",
        queryset=Employee.objects.filter(is_manager=True),
        required=True,
        widget=forms.Select(
            attrs={
                'name': 'validator',
                'class': 'form-control'
            }
        )
    )

    def clean_headline(self):

        headline=self.cleaned_data['headline']

        if headline:
            # check if this headline is already registered
            qs = Task.objects.filter(headline=headline)

            if qs.exists():
                #raise forms.ValidationError(
                #    {'headline': 'Sorry, that headline is already in use, please forward another one'})
                raise forms.ValidationError(
                    'Sorry, that headline is already in use, please forward another one')
        return headline



    def clean_proposal(self):
        proposal = self.cleaned_data['proposal']

        proposal_jsn=json.loads(proposal)
        print(proposal_jsn)
        insert_txt=proposal_jsn['ops'][0]['insert']
        print("proposal: %s" % proposal)
        print("insert_txt: %s" % insert_txt)
        if insert_txt == "\n":
             print("raise exception")
             raise forms.ValidationError(
                'Please, submit here your proposal')

        return proposal

    """
    def clean_proposal(self):
        proposal = self.cleaned_data['proposal']

        print("proposal:")
        print(proposal)
        if proposal:
            content=json.loads(proposal)
        else:
            content={}
        content=content['ops'][0]['insert']

        if content=="\n":
            # check if a proposal has been submitted

            #raise forms.ValidationError(
            #    {'proposal': 'Please, submit here your proposal'})
            raise forms.ValidationError(
                'Please, submit here your proposal')
        return proposal
    """

class EditForm(CreateForm):

    def __init__(self, *args, **kwargs):
        super(EditForm, self).__init__(*args, **kwargs)
        self.fields["headline"].widget.attrs['readonly']= True


    def clean_headline(self):
        headline = self.cleaned_data['headline']

        return headline




class ValidateForm(forms.Form):


    CHOICES=(('1','Waiting for validation'),('2','Accepted'),('5','Refused'))


    validation_choice = forms.ChoiceField(
        widget=forms.RadioSelect(
            attrs={
                'type': 'radio',
                'class': 'flat',
            }
        ),
        choices=CHOICES
    )


    validation_text = forms.CharField(
        label="Comment",
        max_length=1000,
        required=False,
        widget=QuillWidget(
            attrs={
                'placeholder': 'Short description',
                'class': 'form-control has-feedback-left',
            }
        ),
    )

    task_due_date = forms.DateField(
        #input_formats=settings.DATE_INPUT_FORMATS,
        label="Task completion",
        required=True,
        widget=DatePickerWidget()
    )

    standard_update_due_date = forms.DateField(
        #input_formats=settings.DATE_INPUT_FORMATS,
        label="Standard update",
        required=True,
        widget=DatePickerWidget(),
    )

    implementer = forms.ModelChoiceField(
        error_messages={'required': 'Please provide an implementer'},
        label="Implementer",
        #queryset=Employee.objects.filter(manager=self.actor), # list of manager employees
        queryset=Employee.objects, # list of manager employees
        required=True,
        validators=[],
        widget=forms.Select(
            attrs={
                'name': 'implementer',
                'class': 'form-control'
            }
        )
    )

    mailing_list = forms.ModelChoiceField(
        label="Mailing list",
        queryset=Unit.objects,  # list of units
        required=False,
        validators=[],
        widget=forms.Select(
            attrs={
                'name': 'validator',
                'class': 'form-control'
            }
        )
    )
    """
    def clean_standard_update_due_date(self):
        print(self.cleaned_data)
        standard_update_due_date = self.cleaned_data['standard_update_due_date']

        if not standard_update_due_date:
            raise forms.ValidationError(
                'Please provide the date at which standard must be updated')
        return standard_update_due_date

    def clean_task_due_date(self):
        print(self.cleaned_data)
        task_due_date = self.cleaned_data['task_due_date']

        if not task_due_date:
            raise forms.ValidationError(
                'Please provide the due date')
        return task_due_date
    """


class SubmitForm(forms.Form):

    approver = forms.ModelChoiceField(
        error_messages={'required': 'Please provide an approver'},
        label="Approver",
        queryset=Employee.objects.filter(is_manager=True),
        required=True,
        widget=forms.Select(
            attrs={
                'name': 'approver',
                'class': 'form-control'
            }
        )
    )



class ApproveForm(forms.Form):


    approved = forms.BooleanField(
        label="I Approve",
        required=False,
        widget=forms.CheckboxInput(
            attrs={
                'class': 'js-switch',
                'type': 'checkbox'
            }
        )
    )

task/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import Task
from .forms import CreateForm, EditForm, ValidateForm, SubmitForm, ApproveForm
from account.models import Employee





@login_required
def list(request):
    tasks = Task.objects.order_by('creation_date')
    return render(request, 'list_tasks.html', {'tasks': tasks, 'state_choices':Task.state_choices} )


@login_required
def create(request):


    fields=['headline',
            'problem',
            'proposal',
            'validator']

    # get instance of the user that is editing his/her profile
    user = request.user

    # get instance of the employee that is creating the task
    employee = Employee.objects.filter(user__pk=user.pk)[0]


    if request.method == "POST":

        # if user strikes cancel, redirect to task list
        if request.POST.get("cancel"):
            return redirect('task:list')

        # handles form submitted by user
        form = CreateForm(request.POST)

        print("Create form is valid: %r" % form.is_valid() )

        if form.is_valid():

            # get data provided by user
            cleaned_data = form.cleaned_data

            # create new task
            task = Task()
            for field in fields:
                setattr(task, field, cleaned_data[field])

            # add automatic fields and save instance to db
            task.create(employee)

            # if everything goes well, redirect to task list
            return redirect("task:list")

    else:
        # delivers a blank form to be filled in
        form = CreateForm()


    # render form using given html template
    return render(request, 'create_task.html', {'form': form})





@login_required
def edit(request,pk, page):

    forms={'1': CreateForm,
           '2': ValidateForm}

    templates={'1': 'edit_task.html',
               '2': 'validate_task.html'}

    save_functions={'1': 'create',
                    '2': 'validate'}

    actors={'1': 'creator',
            '2': 'validator'}


    form=forms[page]
    template=templates[page]
    save_function=save_functions[page]
    actor=actors[page]
    fields=form.base_fields

    # get task instance
    task = get_object_or_404(Task, pk=pk)

    # get instance of the user whom the request is coming from
    user = request.user

    # get instance of corresponding employee
    employee = Employee.objects.filter(user__pk=user.pk)[0]

    # get task state
    state=task.state

    if request.method == "POST":

        # if user strikes cancel, redirect to task list
        if request.POST.get("cancel"):
            return redirect('task:list')

        # handles form submitted by user
        form = form(request.POST)

        if form.is_valid():

            # get data provided by user
            cleaned_data = form.cleaned_data

            # create new task
            for field in fields:
                setattr(task, field, cleaned_data[field])

            # add automatic fields and save instance to db, with the help of model saving methods (1 method by wizard page)
            save_function=getattr(task,save_function)
            save_function(employee)

            # if everything goes well, redirect to task list
            return redirect("task:list")

    else:

        # create context
        context={field: getattr(task,field) for field in fields}

        # delivers a blank form to be filled in
        form = form(context)


    # render form using given html template
    return render(request, template, {'form': form, 'page': state, 'pk': pk, 'state':state})




@login_required
def edit_wizard(request,pk, page):


    wizard_template='form_wizard.html'

    wizard_titles={'1': 'Propose',
                   '2': 'Validate',
                   '3': 'Submit',
                   '4': 'Approve'}

    forms={'1': EditForm,
           '2': ValidateForm,
           '3': SubmitForm,
           '4': ApproveForm}

    templates={'1': 'edit_task.html',
               '2': 'validate_task.html',
               '3': 'submit_task.html',
               '4': 'approve_task.html'}

    save_functions={'1': 'create',
                    '2': 'validate',
                    '3': 'submit',
                    '4': 'approve'}

    actors={'1': 'creator',
            '2': 'validator',
            '3': 'implementer',
            '4': 'approver'}

    form=forms[page]
    template=templates[page]
    save_function=save_functions[page]
    actor=actors[page]

    fields=form.base_fields

    # get task instance
    task = get_object_or_404(Task, pk=pk)

    # get task state
    state=task.state

    # get instance of the user whom the request is coming from
    user = request.user

    # get instance of corresponding employee
    employee = Employee.objects.filter(user__pk=user.pk)[0]

    # get authorized actor
    authorized_actor=getattr(task,actor)

    # determine writing rights of employee
    is_write=write_permission(page, state, employee, authorized_actor)

    if request.method == "POST":

        # if user strikes cancel, redirect to task list
        if request.POST.get("cancel"):
            return redirect('task:list')

        # handles form submitted by user
        form = form(request.POST)

        #if not is_write:
        #    disable_form(form)
        print("form is valid: %r" % form.is_valid())

        if form.is_valid():

            # get data provided by user
            cleaned_data = form.cleaned_data

            # create new taskviews.py
            for field in fields:
                setattr(task, field, cleaned_data[field])

            # add automatic fields and save instance to db, with the help of model saving methods (1 method by wizard page)
            save_function=getattr(task,save_function)
            save_function(employee)

            # if everything goes well, redirect to task list
            return redirect("task:list")

    else:

        # create context
        context={field: getattr(task,field) for field in fields}

        # delivers a blank form to be filled in
        form = form(context)

        #if not is_write:
        #    print("disable form")
        #    disable_form(form)

    # render form using given html template
    return render(request, template, {'form': form, 'page': page, 'pk': pk, 'wizard_titles':wizard_titles, 'state':state})



def write_permission(page_string, state_string, employee, authorized_actor):

    is_write=False
    print("employee type: %s" % type(employee.pk))
    print("authorized_actor type: %s" % type(authorized_actor.pk))
    print("state type: %s" % type(state_string))
    print(state_string)
    print("page type: %s" % type(page_string))
    state=int(state_string)
    page=int(page_string)
    if employee.pk == authorized_actor.pk:
        if state>=page -1 and state<=page:
            is_write=True


    print("page: %s" % page)
    print("state: %s" % state)
    print("employee: %s" % employee)
    print("authorized_actor: %s" % authorized_actor)



    if is_write:
        print("%s has %s permission" % (employee, page))
    else:
        print("%s has NO %s permission" % (employee, page))

    return is_write



def disable_form(form):
    for field in form.fields:
        #form.fields[field].required=False
        form.fields[field].widget.attrs['disabled'] = 'disabled'


@login_required
def delete(request,pk):

    task = get_object_or_404(Task, pk=pk)

    task.delete()

    return redirect("task:list")

task/templates/approve_task.html
{% extends "form_wizard.html" %}

{% load widget_tweaks %}
{% load static %}


{% block stylesheets %}
  {{ block.super }}
  <link href="{% static "css/validate_task.css" %}" rel="stylesheet">
{% endblock stylesheets %}


{% block wizard_page %}



    <form id="ApproveTaskForm" method="post" action="{% url 'task:edit_wizard' pk=pk page=4 %}" class="form-horizontal form-label-left" novalidate>
        {% csrf_token %}

        <div class="form-group">
            <p style="text-align:center;">

                {{ form.approved}}
                <label>{{ form.approved.label }}</label>

            </p>
        </div>

    </form>
</div>

{% endblock wizard_page %}

{% block javascripts %}
    {{ block.super }}
{% endblock javascripts %}

task/templates/create_task.html
{% extends "base_site.html" %}

{% load widget_tweaks %}
{% load static %}

{% block stylesheets %}
    {{ block.super }}
    {{ form.media.css }}
{% endblock stylesheets %}



{% block title %} Create your account {% endblock title %}


{% block content %}

    <div class="container" style="margin: 10px"><div class="row"><div class="col-md-offset-2 col-md-8 col-xs-12  "><div class="x_panel">
        <div class="x_title">
            <h1>Propose your idea</h1>
        </div>

        <div class="x_content">


            <form id="CreateTaskForm" method="post" action="{% url 'task:create' %}" class="form-horizontal form-label-left" novalidate>
                {% csrf_token %}

                <div class="form-group">
                    <label class="control-label col-md-2 col-sm-2 col-xs-12">{{ form.headline.label }}</label>
                    <div class="col-md-10 col-sm-10 col-xs-12">
                        {% ifequal request.method "POST" %}
                            {% if form.headline.errors %}
                                {% render_field form.headline class="form-control is-invalid" %}
                                {% for error in form.headline.errors %}
                                    <div class="invalid-feedback">
                                        {{ error }}
                                    </div>
                                {% endfor %}

                            {% else %}
                                {% render_field form.headline class="form-control is-valid" %}
                            {% endif %}
                        {% else %}
                            {% render_field form.headline class="form-control" %}
                        {% endifequal %}
                     </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-2 col-sm-2 col-xs-12">{{ form.problem.label }}</label>
                    <div class="col-md-10 col-sm-10 col-xs-12">
                        {% ifequal request.method "POST" %}
                            {% if form.problem.errors %}
                                {% render_field form.problem class="form-control is-invalid" %}
                                {% for error in form.problem.errors %}
                                    <div class="invalid-feedback">
                                        {{ error }}
                                    </div>
                                {% endfor %}

                            {% else %}
                                {% render_field form.problem class="form-control is-valid" %}
                            {% endif %}
                        {% else %}
                            {% render_field form.problem class="form-control" %}
                        {% endifequal %}
                     </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-2 col-sm-2 col-xs-12">{{ form.proposal.label }}</label>
                    <div class="col-md-10 col-sm-10 col-xs-12">
                        {% ifequal request.method "POST" %}
                            {% if form.proposal.errors %}
                                {% render_field form.proposal class="form-control is-invalid" %}
                                {% for error in form.proposal.errors %}
                                    <div class="invalid-feedback">
                                        {{ error }}
                                    </div>
                                {% endfor %}

                            {% else %}
                                {% render_field form.proposal class="form-control is-valid" %}
                            {% endif %}
                        {% else %}
                            {% render_field form.proposal class="form-control" %}
                        {% endifequal %}
                     </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-2 col-sm-2 col-xs-12">{{ form.validator.label }}</label>
                    <div class="col-md-10 col-sm-10 col-xs-12">
                        {% ifequal request.method "POST" %}
                            {% if form.validator.errors %}
                                {% render_field form.validator class="form-control is-invalid" %}
                                {% for error in form.validator.errors %}
                                    <div class="invalid-feedback">
                                        {{ error }}
                                    </div>
                                {% endfor %}

                            {% else %}
                                {% render_field form.validator class="form-control is-valid" %}
                            {% endif %}
                        {% else %}
                            {% render_field form.validator class="form-control" %}
                        {% endifequal %}
                    </div>
                </div>

                <div class="form-group ln_solid"></div>
                     <button id="submit-button" type="submit" name="submit" value="create_task" class="btn btn-success pull-right" >Submit</button>
                     <button id="cancel-button"  type="cancel" name="cancel" value="create_task" class="btn btn-primary pull-right" >Cancel</button>
                </div>

            </form>
        </div>
    </div></div></div></div>



{% endblock content %}

{% block javascripts %}
    {{ block.super }}
    {{ form.media.js }}
{% endblock javascripts %}

task/templates/edit_task.html
{% extends "form_wizard.html" %}

{% load widget_tweaks %}
{% load static %}

{% block stylesheets %}
    {{ block.super }}
    {{ form.media.css }}
{% endblock stylesheets %}


{% block wizard_page %}


    <form id="EditTaskForm" method="post" action="{% url 'task:edit_wizard' pk=pk page=1 %}" class="form-horizontal form-label-left" novalidate>
        {% csrf_token %}

        <div class="form-group">
            <label class="control-label col-md-2 col-sm-2 col-xs-12">{{ form.headline.label }}</label>
            <div class="col-md-10 col-sm-10 col-xs-12">
                {% ifequal request.method "POST" %}
                    {% if form.headline.errors %}
                        {% render_field form.headline class="form-control is-invalid" %}
                        {% for error in form.headline.errors %}
                            <div class="invalid-feedback">
                                {{ error }}
                            </div>
                        {% endfor %}

                    {% else %}
                        {% render_field form.headline class="form-control is-valid" %}
                    {% endif %}
                {% else %}
                    {% render_field form.headline class="form-control" %}
                {% endifequal %}
             </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2 col-sm-2 col-xs-12">{{ form.problem.label }}</label>
            <div class="col-md-10 col-sm-10 col-xs-12">
                {% ifequal request.method "POST" %}
                    {% if form.problem.errors %}
                        {% render_field form.problem class="form-control is-invalid" %}
                        {% for error in form.problem.errors %}
                            <div class="invalid-feedback">
                                {{ error }}
                            </div>
                        {% endfor %}

                    {% else %}
                        {% render_field form.problem class="form-control is-valid" %}
                    {% endif %}
                {% else %}
                    {% render_field form.problem class="form-control" %}
                {% endifequal %}
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2 col-sm-2 col-xs-12">{{ form.proposal.label }}</label>
            <div class="col-md-10 col-sm-10 col-xs-12">
                {% ifequal request.method "POST" %}
                    {% if form.proposal.errors %}
                        {% render_field form.proposal class="form-control is-invalid" %}
                        {% for error in form.proposal.errors %}
                            <div class="invalid-feedback">
                                {{ error }}
                            </div>
                        {% endfor %}

                    {% else %}
                        {% render_field form.proposal class="form-control is-valid" %}
                    {% endif %}
                {% else %}
                    {% render_field form.proposal class="form-control" %}
                {% endifequal %}
             </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2 col-sm-2 col-xs-12">{{ form.validator.label }}</label>
            <div class="col-md-10 col-sm-10 col-xs-12">
                {% ifequal request.method "POST" %}
                    {% if form.validator.errors %}
                        {% render_field form.validator class="form-control is-invalid" %}
                        {% for error in form.validator.errors %}
                            <div class="invalid-feedback">
                                {{ error }}
                            </div>
                        {% endfor %}

                    {% else %}
                        {% render_field form.validator class="form-control is-valid" %}
                    {% endif %}
                {% else %}
                    {% render_field form.validator class="form-control" %}
                {% endifequal %}
            </div>
        </div>

    </form>
</div>

{% endblock wizard_page %}


{% block javascripts %}
    {{ block.super }}
    {{ form.media.js }}
{% endblock javascripts %}

task/templates/list_tasks.html
{% extends 'base_site.html' %}

{% load custom_filters %}


{% block title %} List tasks {% endblock title %}


{% block stylesheets %}
  {{ block.super }}
  <link href="/static/dashboard/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet">
  <link href="/static/dashboard/vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css" rel="stylesheet">
  <link href="/static/dashboard/vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css" rel="stylesheet">
  <link href="/static/dashboard/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css" rel="stylesheet">
  <link href="/static/dashboard/vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css" rel="stylesheet">
{% endblock stylesheets %}



{% block content %}

    <div class="x_panel">
        <div class="x_title">
            <ul class="nav navbar-left panel_toolbox">
                <li><h1>Tasks<a href="{% url 'task:create' %}"> <span class="glyphicon glyphicon-plus"></span></a></h1></li>
            </ul>
        </div>
        <div class="x_content">

            {% if tasks %}

                <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th>Idea</th>
                            <th>Status</th>
                            <th>Creator</th>
                            <th>Created on</th>
                            <th class="no-sort"></th>
                        </tr>
                    </thead>

                    <tbody>
              {% for task in tasks %}
                  {% with state_minus_1=task.state|add:"-1" %}
                  {% with state=state_choices|index:state_minus_1|index:1 %}
                        <tr>
                            <td><a href="{% url 'task:edit_wizard' pk=task.pk page=1 %}">{{task.headline}}</a></td>
                            <td><a href="#">{{state}}</a></td>
                            <td><a href="#">{{task.creator.user.get_username}}</a></td>
                            <td><a href="#">{{task.creation_date}}</a></td>
                            <td><a href="{% url 'task:delete' task.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
                        </tr>
                  {% endwith %}
                  {% endwith %}
              {% endfor %}
                    </tbody>
                </table>

            {% else %}
                No idea has been submitted
            {% endif %}

        </div>
    </div>


{% endblock content%}



{% block javascripts %}
    {{ block.super }}
    <!-- Datatables -->
    <script src="/static/dashboard/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="/static/dashboard/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <script src="/static/dashboard/vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="/static/dashboard/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>
    <script src="/static/dashboard/vendors/datatables.net-buttons/js/buttons.flash.min.js"></script>
    <script src="/static/dashboard/vendors/datatables.net-buttons/js/buttons.html5.min.js"></script>
    <script src="/static/dashboard/vendors/datatables.net-buttons/js/buttons.print.min.js"></script>
    <script src="/static/dashboard/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
    <script src="/static/dashboard/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
    <script src="/static/dashboard/vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
    <script src="/static/dashboard/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>
    <script src="/static/dashboard/vendors/datatables.net-scroller/js/dataTables.scroller.min.js"></script>
    <script src="/static/dashboard/vendors/jszip/dist/jszip.min.js"></script>
    <script src="/static/dashboard/vendors/pdfmake/build/pdfmake.min.js"></script>
    <script src="/static/dashboard/vendors/pdfmake/build/vfs_fonts.js"></script>

    $(document).ready(function(){
        $('#list').DataTable();
    });

{% endblock javascripts %}